server: 
  port: 11222
  address: 0.0.0.0
  http2.enabled: true
  tomcat.uri-encoding: utf-8
spring:
  # ====================redis====================
  redis:
    # Redis服务器地址
    host: #######
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: ####################################
    # 连接超时时间（毫秒）
    timeout: 50000
    # Redis数据库索引（默认为0）
    database: 0
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
  # ====================mvc==================== #
  mvc:
    view:
      prefix: "pages"
      suffix: ".jsp"
logging:
  level:
    com.sunsulei.v2ex: debug